### ISSUE TITLE
Build failure plots-0.1.0.0

### ISSUE THREAD

**Issue by ggreif** [cchalmers/plots#19]
Thanks for writing this lib, but building it failed :-(

```
[19 of 23] Compiling Plots.Types.HeatMap ( src/Plots/Types/HeatMap.hs, dist/build/Plots/Types/HeatMap.o )

src/Plots/Types/HeatMap.hs:86:38:
    Not in scope: type constructor or class ‘Vector’
    Perhaps you meant one of these:
      ‘S.Vector’ (imported from Data.Vector.Storable),
      ‘V.Vector’ (imported from Data.Vector.Unboxed),
      ‘M.MVector’ (imported from Data.Vector.Generic.Mutable)

src/Plots/Types/HeatMap.hs:265:32:
    Not in scope: type constructor or class ‘Vector’
    Perhaps you meant one of these:
      ‘S.Vector’ (imported from Data.Vector.Storable),
      ‘V.Vector’ (imported from Data.Vector.Unboxed),
      ‘M.MVector’ (imported from Data.Vector.Generic.Mutable)
cabal: Leaving directory '/var/folders/k9/fj_1d5h17m7c4gbyp2srqrhm0000gq/T/cabal-tmp-56761/plots-0.1.0.0'
Failed to install plots-0.1.0.0
cabal: Error: some packages failed to install:
plots-0.1.0.0 failed during the building phase. The exception was:
ExitFailure 1
```

**Comment by ggreif** [comment]
I should note that I do not have the latest `haskell-platform` installed:

``` shell
$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 7.10.3
```

**Comment by cchalmers** [comment]
Hmm, I should have set up travis. I can see that it should be `V.Vector`, I'm just sure why mine _is_ building. 🤔

**Comment by cchalmers** [comment]
I've pushed the fix, hope it works now. I'm still not sure why I'm not getting the error. I seem to be pulling `Vector` in from `Diagrams.Prelude` but that doesn't make any sense.

**Comment by hvr** [comment]
I'm afraid there's still build errors, e.g. with GHC 7.8

```
[ 3 of 23] Compiling Plots.Util       ( src/Plots/Util.hs, /tmp/matrix-worker/1479663988/dist-newstyle/build/x86_64-linux/ghc-7.8.4/plots-0.1.0.1/build/Plots/Util.o )
[ 4 of 23] Compiling Diagrams.Coordinates.Polar ( src/Diagrams/Coordinates/Polar.hs, /tmp/matrix-worker/1479663988/dist-newstyle/build/x86_64-linux/ghc-7.8.4/plots-0.1.0.1/build/Diagrams/Coordinates/Polar.o )
[ 5 of 23] Compiling Plots.Axis.Scale ( src/Plots/Axis/Scale.hs, /tmp/matrix-worker/1479663988/dist-newstyle/build/x86_64-linux/ghc-7.8.4/plots-0.1.0.1/build/Plots/Axis/Scale.o )

src/Plots/Axis/Scale.hs:285:30:
    Not in scope: type constructor or class ‘Foldable’
```

and with GHC 7.6

```
Configuring component lib from plots-0.1.0.1
Preprocessing library plots-0.1.0.1...
[ 1 of 23] Compiling Diagrams.Coordinates.Isomorphic ( src/Diagrams/Coordinates/Isomorphic.hs, /tmp/matrix-worker/1479663994/dist-newstyle/build/x86_64-linux/ghc-7.6.3/plots-0.1.0.1/build/Diagrams/Coordinates/Isomorphic.o )

src/Diagrams/Coordinates/Isomorphic.hs:55:30:
    Expecting one more argument to `v'
    In the class declaration for `VectorLike'
```

May I suggest giving

https://github.com/hvr/multi-ghc-travis/blob/master/make_travis_yml_2.hs

a try?

**Comment by cchalmers** [comment]
@hvr Thanks, I'll try that.

**Comment by cchalmers** [comment]
Thanks for the help. I finally got a [successful build](https://travis-ci.org/cchalmers/plots/builds/177503952) in 7.8. I've uploaded [plots-0.1.0.2](http://hackage.haskell.org/package/plots-0.1.0.2) to hackage.

Let me know if there's any other problems.

**Comment by hvr** [comment]
@cchalmers well, the problem with GHC 7.6 I mentioned earlier is still existing...

**Comment by cchalmers** [comment]
Ah, sorry missed that. I don't think I'll support 7.6. I don't even know how to fix that error.

**Comment by cchalmers** [comment]
That's a lie, I do know how to fix that error. But I also use `:~:` for some of my traversals, which was introduced in `7.8`. I could implement it myself but then there may be other problems.

I guess could still offer 7.6 support if there's demand for it.

**Comment by ggreif** [comment]
Thanks for fixing it so swiftly!

**Comment by hvr** [comment]
@cchalmers it's totally ok not to support GHC 7.6 if you don't want to; just set a lower bound on `base` to declare where your support ends
