### ISSUE TITLE
Legend bug when using `diagrams-postscript` backend

### ISSUE THREAD

**Issue by ocramz** [cchalmers/plots#30]
![image](https://cloud.githubusercontent.com/assets/5902760/21289833/274cca68-c4a7-11e6-869b-bc32b30d899e.png)

When rendering with the EPS backend, the legend renders as a black rectangle.

^ This plot was obtained with the usual `-o plot.eps` option : `stack exec sde-plot -- hist 500 0.0042 0.991 0.104 1.885 -o hist.eps`

```
histPlot :: String -> [Double] -> IO (Axis B V2 Double)
histPlot descStr d = execStateT ?? r2Axis $ do
       histogramPlot d $ do
         key descStr
         plotColor .= blue
         areaStyle . _opacity .= 0.5
         numBins .= 20
       legendStyle . _lw .= 0
       legendTextWidth *= 4
```

**Comment by cchalmers** [comment]
This happened because I filled the legend box with a transparent fill but postscript doesn't support transparency.  I've removed that line and it seems to be fine now.
