### ISSUE TITLE
Overlay other diagrams on plots

### ISSUE THREAD

**Issue by idontgetoutmuch** [cchalmers/plots#32]
I'd like to overlay a symbol representing Jupiter and a symbol representing the Sun on a line plot. I'll add more details on this later.

![jupiter-sun-line](https://user-images.githubusercontent.com/1550265/28407379-dd76c97e-6d2b-11e7-8e9f-fa388067bdc7.png)

**Comment by cchalmers** [comment]
There are two ways you could do this:

  - you can use you `Plotable` instance for `Diagram` to add a planet, using [`addPlotable'`](https://hackage.haskell.org/package/plots-0.1.0.2/docs/Plots-Axis.html#v:addPlotable-39-)
  - you could use a scatter plot with one point and change the [`plotMarker`](https://hackage.haskell.org/package/plots-0.1.0.2/docs/Plots-Style.html#v:plotMarker) to be the planet  (you'd need a separate `ScatterPlot` for each planet)

(I did say this on irc while it said you where online but I guess you weren't. I'm also finding IRC annoying now the logs are down.)

**Comment by idontgetoutmuch** [comment]
Something like this :)
![jupiter-sun-line](https://user-images.githubusercontent.com/1550265/28431863-bacc1170-6d7d-11e7-9cd5-0785f7175f06.png)

**Comment by idontgetoutmuch** [comment]
Since you @cchalmers have solved my problem for me, I will close the issue :+1:
