### ISSUE TITLE
not in scope: zeroy in area.hs

### ISSUE THREAD

**Issue by bollu** [cchalmers/plots#4]
I'm trying to play around with plots, so I was compiling `examples/area.hs`. I get the error:

```
/Users/bollu/work/haskell-plots-source/examples/area.hs:19:28:
    Not in scope: ‘zeroy’
    Perhaps you meant ‘zero’ (imported from Diagrams.Prelude)
```

does `zeroy` refer to something? if so, what?

**Comment by cchalmers** [comment]
Looks like not all the examples work. I'll get those fixed.

`zeroy` is a function to make all the `y` values 0. It's used to complete the area path. Not sure why it's not there.

**Comment by bollu** [comment]
I'm creating a `stack` file for all the examples, so you can use `stack` with the `plots` library

**Comment by cchalmers** [comment]
Great. Sounds good.
