### ISSUE TITLE
No HasMinorGridLines instance for ColourBar

### ISSUE THREAD

**Issue by GregorySchwartz** [cchalmers/plots#42]
No `HasMinorGridLines` instance for `ColourBar`, and `ColourBar` fields are not exported -- needs to export `ColourBar (..)`.

**Comment by GregorySchwartz** [comment]
Additionally, no style is applied to the ticks for the bar.

**Comment by cchalmers** [comment]
I've added minor ticks to the colour bar (8f95b5f74610f68d653e0ceed0bbdc5f6c76742e).

I don't really want to export the fields of `ColourBar`, it makes preventing breaking changes much hard (like adding a new field) and the internals are kinda murky. Is there another way to get what you want?

I'm not sure what you mean about the style, it [does get applied](https://github.com/cchalmers/plots/blob/master/src/Plots/Axis/ColourBar.hs#L269). Note that each of the ticks have their own style so you have to set them explicitly.

**Comment by GregorySchwartz** [comment]
Sorry, looking at the GitHub code I meant `HasMajorGridLines`, not `HasMinorGridLines`. The style not being applied was for the hackage version it seems (can that get an update?). I wanted the export because of the missing instance, really, as I wanted to hide the lines in the color bar (not the ticks, which I wanted the style for to make thicker).

**Comment by cchalmers** [comment]
Ah OK, I've added the instance (fc6667e) and uploaded it to Hackage.

**Comment by GregorySchwartz** [comment]
Works perfectly, thank you!
