### ISSUE TITLE
Containers upper bound

### ISSUE THREAD

**Issue by adamConnerSax** [cchalmers/plots#43]
Thanks for the cool library!

The current version has a containers upper-bound of < 0.6.0.0 but, at least as far as I can tell, the library works fine with containers-0.6.

It's easy enough to work around with cabal-project and allow-newer but it makes things difficult for releasing a library with a dependence on plots since then we force everyone downstream to do the "allow-newer" dance as well.  Could that bound be updated in plots?

**Comment by cchalmers** [comment]
Sorry for the slow response. I did actually already bump the version a few weeks ago, I just didn't upload it to hackage. I've done that now: https://hackage.haskell.org/package/plots-0.1.1.1

**Comment by adamConnerSax** [comment]
Thanks!  In the next knit-haskell release, I'll add a plots example.

**Comment by cchalmers** [comment]
Awesome!
