### ISSUE TITLE
Custom NanColours

### ISSUE THREAD

**Issue by bjartur** [cchalmers/plots#45]
<dl>
<dt><i>Personne</i></dt><dd>Library consumer (statistician plotting interesting data)</dd>
<dt><i>Objectif</i></dt><dd>Create a ColourMap with custom NanColours</dd></dl>

#### <i>Méthode essayée</i>

```
import Data.Colour.Names( black, blue, magenta, red, white )
import Data.Map( fromList )
import Plots.Style(
    ColourMap(ColourMap),
    NanColours(_infColour, _negInfColour, _axisColourMap)
    )
grey:: ColourMap
grey= ColourMap
  NanColours { _nanColour=magenta, _infColour=red, _negInfColour=blue }
  $ fromList [(0,white), (1,black)]
```
<dl><dt>Problème</dt> Neither the ColourMap constructor nor the NanColours field accessors are exported. NanColours can thus only be defined within the Plots.Style module itself, and cannot be customized </dd></dl>

**Comment by cchalmers** [comment]
You can use the lenses in class [`HasNanColours`](http://hackage.haskell.org/package/plots-0.1.1.2/docs/Plots-Style.html#t:HasNanColours).

```
myColourMap = colourMap [(0, white), (1, black)]
  & nanColour .~ magenta
  & infColour .~ red
  & negInfColour .~ blue
```

**Comment by bjartur** [comment]
Thanks! You're absolutely right.
